name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## We love hearing improvement ideas!

  - type: input
    id: title
    attributes:
      label: Feature title
      placeholder: Short summary of the feature

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how you'd imagine it working
      placeholder: Add CLI flag, change header behavior, etc.

  - type: checkboxes
    id: accept_prs
    attributes:
      label: Contribution
      options:
        - label: I'm interested in helping implement this


